<!--#include file="assets/includes/inc_header_common.asp"-->

        <div class="box100">
            <h2>History of the Police Department</h2>
            <p>The Town of Greenville created a full-time Police Department in December of 1971. Edmond &#8220;Bud&#8221; Pelletier was hired as Chief of Police. The police department office was located at this time in the north side of the town garage.</p>
            <p>1972 - Chief Pelletier graduated from Maine Criminal Justice Academy. Police Chief Pelletier designed the very popular patch for this department. It consists of a moose, pine trees, Moosehead Lake along with DIRIGO imprinted on it.</p>
            <p>1973 - In the spring of the year, this department installed new type radio equipment that made contacting other law agencies in the state. Newly appointed reserve officers were, Ed Lambert, Alan McBrierty, Ronald Jones and Nester &#8220;Terry&#8221; Beckwith. Chief Pelletier held the first Bike Safety Course at the school grounds.</p>
            <p>In 1974 the toll-free number to Piscataquis County Sheriff was installed for emergencies. Residents called this number for fire and/or police emergencies. They would then radio the needed help. Constables in 1974 were Walter Crossman Jr., John Owens, and Edward Lambert. An agreement was also established with Piscataquis to assist Greenville with patrols and extra help. The biggest complaints that this department had were dog complaints. A drug program was instituted through this department and the school. Reason for Tears was distributed throughout the community for the families to read. Fingerprinting kit and new Polaroid camera were purchased.</p>
            <p>In 1976 with the assist of state funds a dog pound was built and put on Edward Lambert&#8217;s property. Mr. Lambert was the dog constable at the time. Greenville Police Department applied for and received through a federal grant to hire another officer due to increased workload of this department. Maxim &#8220;Mickey&#8221; Squiers was hired under this federal funded program and then funded thereafter through the town. The town purchased a new cruiser, a 1977 Plymouth Fury.</p>
            <p>In 1978, this department held meetings with school board, citizens and other law enforcement personnel in reference to a drug program. With this program, we hope that the drug problems will slow down, but unfortunately will always be there. A check of $1000. was donated to this department from Beaver Cove. This was done due to the patrolling of the area from this department.</p>
            <p>In 1979, Kathi Mullin, a registered nurse with Charles A. Dean Memorial was appointed Matron of the Greenville Police Department. She was the first female hired for this position. When a female suspect needed to be transported, we would have Kathi ride with us.</p>
            <p>In 1981, Edmond &#8220;Bud&#8221; Pelletier retires as Greenville&#8217;s Police Chief. Maxim &#8220;Mickey&#8221; Squiers took over for Bud as Chief of Police. Due to the continuing dog problem in Greenville, a dog policy is in the process of being written. This will hopefully slow down the complaints. Edmond &#8220;Bud&#8221; Pelletier was honored as being selected Police Chief of the year. Chief Pelletier was the first certified police chief in Piscataquis County.</p>
            <p>In 1982, due to budget cuts, the police department was cut from two full-time officers to one full-time officer. Piscataquis and the State Police assisted us in patrol and extra help. The new OUI laws became in effect this year, and have resulted in fewer OUI arrests in this area. Although we didn&#8217;t have a lot, we do have fewer than we did.</p>
            <p>In 1985, we purchased a new cruiser to replace the 1982 Ford Fairmont. The department purchased a 1985 Dodge Diplomat. The Greenville Police Department sponsored a Reserve Officer&#8217;s Training course through the Maine Criminal Justice Academy. Anyone who wishes to work as a reserve officer must take this training course. Robert Lavigne was hired as a constable.</p>
            <p>In 1986, Nick White and Mike Canders were hired on as new reserves. Nick White comes to us from Washington, DC where he worked as an officer and Mike Canders who works for the Border Patrol, works for us during the weekends.</p>
            <p>In 1989, Frank Heaney gets hired as a full-time officer. Mitchell Thornton and Harry Doughty graduate from the reserve officers training at the Maine Criminal Justice Academy.</p>
            <p>In 1991, new reserves are hired. John Carroll, Dan Carroll and Tom Jordon. Other reserves for this department are Gray &#8220;Bump&#8221; Morrison, Grayln Smith, Manuel &#8220;Manny&#8221; Mendes and Kent Stevens was hired as this area Animal Control Officer.</p>
            <p>In 1993, Bill Chandler was hired as a reserve. Maxim &#8220;Mickey&#8221; Squiers retires as Chief of Police. In the Interim, head selectmen, Paul Fichtner, MD did all administrative work. Duane D. Alexander was hired in November of 1993 to replace Chief Squiers.</p>
            <p>In 1996, Chief Alexander graduated as an instructor for the D.A.R.E. program. This is a drug awareness program that is taught for students in the Kindergarten through 5th grade. These classes are still going on to this date. This year&#8217;s Junior Class was Chief Alexander&#8217;s first D.A.R.E. class. Each year we have the schools give us two names, one lady and one gentleman from the Junior Class to have as D.A.R.E. role models for the 5th grade class. Guy Dow was hired as a full-time officer. Other officers that held positions as reserves are Mike Canders, Melvin Graves, William Jones, Jr., Paul Davis, Steve Hinkley, Larry Morrill, Steve Wipperman, Craig Johnson and Animal Control Officer Kent Stevens. Secretary for the Police Department is Sharon Libby Jones. In December of 1996, Mary Fowle was hired as Secretary.</p>
            <p>In 1997, Milford Rice was hired as full-time officer, replacing Guy Dow. The Greenville Police Department enrolled in a program called, Enhanced Neighborhood Policing. This department is the first police department in Piscataquis County to be enrolled in such a program. Members are Chief Alexander, Officer Milford Rice, Selectman, Bonnie DuBien and Union 60 Guidance Counselor, David Morrill.</p>
            <p>In 1998, 29 residents were selected to be involved in the Enhanced Neighborhood Policing. The group chose the name: M.A.N.P.A.C. (Moosehead Area Neighborhood Policy Advisory Committee).</p>
            <p>In 1999, MANPAC targeted the problem with juveniles obtaining alcohol. Area businesses along with media, helped in promoting this program by adhering bright pink stickers to all alcohol they sold that read: &#8220;If you provide, you&#8217;ll take a ride.&#8221; This program helped to lower the violations by 45%. MANPAC also started another program called &#8220;Restorative Justice Program&#8221;. This was used for first time juvenile offenders to have the option of facing their victims, parent, police and MANPAC members instead of going to juvenile court.</p>
            <p>In 2000, David Johnson was hired to replace Milford Rice as full-time officer. Charles A. Runnels was hired as a full-time/part-time officer.</p>
            <p>In 2002, The police department received through the LOCATER grant program, which is the National Center for Missing and Exploited Children Program, a new computer, printer and scanner. With this program, we are alerted when there is a missing child or adult (AMBER ALERT). With this program, we are able to generate and electronically post photos and pertinent information of missing children and adults.</p>
            <p>In 2003, We were able to replace the 2000 Jeep cruiser with a 2004 GMC 4-door truck. We received money from an anonymous donor to enable us to purchase the truck. Ricky Craven also provided $2,500 to outfit it. A new bed liner was donated by another anonymous source. We also received a used vehicle cage surplus property from the Peabody, Massachusetts Police Department. We also partnered with IF&amp;W to secure funds for a new patrol boat. The boat was delivered in early summer of 2003. In November 2003, Bethany Young was hired as Police Secretary.</p>
            <p>In July of 2004, Charles Runnels was promoted to Corporal, replacing David Johnson. James Emerson of Corinna was hired as a reserve officer. We also received over $7,000 in a Homeland Security Grant, with which we used to purchase a radio tower and base radio.</p>
            <p>In January of 2005, The Police Department was moved from 10 Minden Street to 7 Minden Street in the newly constructed Town Office. The Police Department now has a Booking/Interview Room, Squad Room, Chief&#8217;s Office and Entry Area. This new space was greatly needed.</p>
            <p>The department also has a bicycle registration program and all cyclists are encouraged to register their bikes at the police department. We are hoping that registrations of bicycles will expedite the process of locating lost or stolen bicycles. This department assists the Greenville Recreation Department with a bike rodeo. During the summer months, for the past 5 years, we have been giving out ice cream coupons to all children &#8220;caught wearing&#8221; their bike helmets while riding their bikes. This again is through the generosity of a local business.</p>
            <p>With the retiring of Corporal Runnels in 2006 the department had to sit down and look at rescheduling officers. It was agreed upon that there was now a need to have two full time Officers and one Full/Part time Officer as well as Reserve Officers. This made way for the Department to hire Scott MacMaster as Sergeant and Charles Runnels as the Full-Partime Corporal. In the Spring of 2006 both Chief Duane Alexander and Corporal Charles Runnels retired from the Greenville Police Department to pursue other endeavors. Scott MacMaster was hired to fill the Chief&#8217;s position which then left the Sergeants position which was soon filled by Julian Harwood. In the winter of 2006 Julian Harwood stepped down as Sergeant and Jeff Pomerleau of Augusta took the position over.</p>
            <p>In January of 2010 Scott MacMaster left the Greenville Police Department leaving the Chief's position open. Jeff Pomerleau was hired to take the Police Chief position shortly there after. In July of 2010 four new reserves were brought on board. John Matula of Ohio was hired as a Patrolman.</p>
            <p>In March of 2011 John Matula left the Greenville Police Department to move back to Ohio. Reserve Matthew St. Laurent was hired to take John&#8217;s place as Patrolman. The Greenville Police Department began &#8220;Operation Sunrise&#8221; an outreach program designed to monitor the well being of the communities Senior and disabled members. Each day the Greenville Police Department contacts the individuals who have signed up for the program either through a phone call or a visit to be sure everything is ok.</p>
            <p>In January of 2012 Matt St. Laurent went to the Police Academy and graduated in May.</p>
            <p>In September of 2013 K-9 Natalie came on board with the Greenville Police Department and worked throughout the first year towards her certification for Felony Tracking.</p>
            <p>Lt. Matthew St. Laurent stepped down as Lieutenant and went to Reserve status. In September of 2014 K-9 Natalie &amp; Matthew St. Laurent received certification for Felony Tracking. Also, in September James Carr was hired to fill the Lieutenant position. Michael Jewett and Keith Brann were also hired as reserves.</p>
            <p>In July 2017 Nick Clukey stepped up from part-time Reserve Officer to Part-time/Full-time Reserve Officer.</p>

        </div>

        <div class="clearfix"></div>


<!--#include file="assets/includes/inc_footer_common.asp"-->